/**
 * Rule-based linguistic pattern matcher (thesis FR-DET-03).
 *
 * A candidate (s, r) is generated by the rule's lexical trigger L(s, r) and is
 * flagged (D(s, r) = 1) only if it also satisfies the rule's structural/POS
 * condition S(s, r) AND its local contextual condition C(s, r).
 *
 * options.mode = "lexicalOnly" skips S and C and returns every candidate. That
 * is the thesis' section 8.3 keyword baseline: Candidate(s, r) = L(s, r).
 *
 * Quoted speech: a candidate that lies entirely inside quotation marks is what
 * a source said, not the outlet's own wording, so it is not flagged
 * (failedAt = "quoted"). A rule can opt back in with `flagInsideQuotes: true`
 * (slogans are usually quoted), and options.includeQuotes = true disables the
 * check. The keyword baseline (mode "lexicalOnly") is unaffected.
 *
 * Pure function module (no DOM, no chrome.*) so it is unit-testable under Node.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    var nlpDep;
    try {
      nlpDep = require("../lib/compromise.js");
    } catch (e) {
      nlpDep = null;
    }
    module.exports = factory(nlpDep);
  } else {
    root.PatternMatcher = factory(root.nlp);
  }
})(typeof self !== "undefined" ? self : this, function (nlpFn) {
  "use strict";

  if (typeof nlpFn !== "function") {
    throw new Error(
      "PatternMatcher: compromise.js `nlp` function was not found. " +
        "Make sure lib/compromise.js is loaded before content/pattern-matcher.js."
    );
  }

  var TIER_RANK = { high: 3, medium: 2, low: 1 };
  var QUANTITY_TAGS = ["Value", "Percent", "Money"];
  var LINGUISTIC_TYPES = [
    "none", "all", "any", "not", "taggedAny", "precedesNoun", "followedByTag",
    "precededByTag", "followedByWord", "reportingVerb", "inQuestion"
  ];

  function norm(s) {
    return (s || "").toLowerCase().replace(/\s+/g, " ").trim();
  }

  // A literal space in a rule must also match line breaks / runs of spaces / NBSP: paragraph
  // textContent keeps the page source's raw whitespace, which browsers collapse visually.
  function spaced(source) {
    return source.replace(/ /g, "\\s+");
  }

  function hasTag(term, tag) {
    return !!term && Array.isArray(term.tags) && term.tags.indexOf(tag) !== -1;
  }

  function hasAnyTag(term, tags) {
    if (!term || !tags) return false;
    for (var i = 0; i < tags.length; i++) if (hasTag(term, tags[i])) return true;
    return false;
  }

  function inList(word, list) {
    var w = norm(word);
    for (var i = 0; i < (list || []).length; i++) if (norm(list[i]) === w) return true;
    return false;
  }

  /**
   * Flattens compromise's per-sentence offsets into one term list whose
   * offset.start/length are absolute positions in `text`. Each term carries
   * its sentenceIndex; terms.sentences[i] = { first, last } term indexes.
   */
  function flattenTerms(text) {
    var sentences = nlpFn(text).out("offsets");
    var terms = [];
    terms.sentences = [];
    for (var s = 0; s < sentences.length; s++) {
      var sentTerms = sentences[s].terms || [];
      var first = terms.length;
      for (var t = 0; t < sentTerms.length; t++) {
        sentTerms[t].sentenceIndex = s;
        terms.push(sentTerms[t]);
      }
      terms.sentences.push({ first: first, last: terms.length - 1 });
    }
    return terms;
  }

  /** Indexes [first, last] of the terms that overlap the character span, or null. */
  function termRange(terms, start, end) {
    var a = -1;
    var b = -1;
    for (var i = 0; i < terms.length; i++) {
      var s = terms[i].offset.start;
      var e = s + terms[i].offset.length;
      if (s < end && e > start) {
        if (a < 0) a = i;
        b = i;
      } else if (a >= 0) {
        break;
      }
    }
    return a < 0 ? null : [a, b];
  }

  function sameSentence(terms, i, j) {
    return !!terms[i] && !!terms[j] && terms[i].sentenceIndex === terms[j].sentenceIndex;
  }

  /** S(s, r): structural / POS condition around the candidate's term range. */
  function evalLinguistic(cond, ctx) {
    if (!cond || !cond.type || cond.type === "none") return true;
    var t = ctx.terms;
    var a = ctx.a;
    var b = ctx.b;
    var k;
    var n;

    switch (cond.type) {
      case "all":
        for (k = 0; k < cond.of.length; k++) if (!evalLinguistic(cond.of[k], ctx)) return false;
        return true;
      case "any":
        for (k = 0; k < cond.of.length; k++) if (evalLinguistic(cond.of[k], ctx)) return true;
        return false;
      case "not":
        return !evalLinguistic(cond.of, ctx);
      case "taggedAny":
        return hasAnyTag(t[a], cond.tags);
      case "precedesNoun":
        return sameSentence(t, b, b + 1) && hasTag(t[b + 1], "Noun");
      case "followedByTag":
        for (k = 1; k <= (cond.within || 1); k++) {
          if (!sameSentence(t, b, b + k)) return false;
          if (hasAnyTag(t[b + k], cond.tags)) return true;
        }
        return false;
      case "precededByTag":
        for (k = 1; k <= (cond.within || 1); k++) {
          if (!sameSentence(t, a, a - k)) return false;
          if (hasAnyTag(t[a - k], cond.tags)) return true;
        }
        return false;
      case "followedByWord":
        for (k = 1; k <= (cond.within || 1); k++) {
          if (!sameSentence(t, b, b + k)) return false;
          if (inList(t[b + k].normal || t[b + k].text, cond.words)) return true;
        }
        return false;
      case "reportingVerb":
        // Introduces a statement: followed by "that" or an opening quotation mark,
        // not used in an unrelated sense ("admitted to the hospital").
        n = t[b + 1];
        if (n && norm(n.normal || n.text) === "that") return true;
        return /^\s*["“'‘]/.test(ctx.text.slice(ctx.end, ctx.end + 4));
      case "inQuestion":
        n = t[ctx.sentence.last];
        return !!n && /\?/.test(n.post || "");
      default:
        return false;
    }
  }

  var SINGLE_QUOTE_RE = /(^|[\s(\[\u2014\u2013-])(['\u2018])(?=\S)((?:[^'\u2018\u2019\n]|['\u2019](?=\w)){2,200}?)(?<=\S)(['\u2019])(?=$|[\s.,;:!?)\]\u2014\u2013-])/g;

  /**
   * [start, end) character ranges that lie inside quotation marks (marks excluded).
   * Double quotes: curly open/close or straight toggle. A quote opened and not closed
   * runs to the end of the paragraph (the news convention for multi-paragraph quotes).
   * Single quotes (headline style) count only where they open a word and close one.
   */
  function quotedSpans(text) {
    var spans = [];
    var open = false;
    var from = 0;
    var sawOpener = false;
    for (var i = 0; i < text.length; i++) {
      var ch = text.charAt(i);
      if (ch === "\u201C" || (ch === '"' && !open)) {
        if (!open) { open = true; from = i + 1; sawOpener = true; }
      } else if (ch === "\u201D" || (ch === '"' && open)) {
        if (open) { spans.push([from, i]); open = false; }
        else if (!sawOpener && !spans.length) spans.push([0, i]); // closes a quote opened in an earlier paragraph
      }
    }
    if (open) spans.push([from, text.length]);
    var re = new RegExp(SINGLE_QUOTE_RE.source, "g");
    var m;
    while ((m = re.exec(text)) !== null) {
      var s = m.index + m[1].length + 1;
      var e = s + m[3].length;
      var overlaps = spans.some(function (x) { return s < x[1] && e > x[0]; });
      if (!overlaps) spans.push([s, e]);
    }
    return spans;
  }

  function insideQuote(spans, start, end) {
    for (var i = 0; i < spans.length; i++) if (start >= spans[i][0] && end <= spans[i][1]) return true;
    return false;
  }

  /** C(s, r): local contextual condition. Every key present must hold. */
  function evalContext(cond, ctx) {
    if (!cond) return true;
    var t = ctx.terms;
    var a = ctx.a;
    var b = ctx.b;
    var i;

    if (cond.excludeNeighborWords) {
      if (t[a - 1] && inList(t[a - 1].normal || t[a - 1].text, cond.excludeNeighborWords)) return false;
      if (t[b + 1] && inList(t[b + 1].normal || t[b + 1].text, cond.excludeNeighborWords)) return false;
    }
    if (cond.excludeWindowWords) {
      var w = cond.excludeWindowWords;
      for (i = Math.max(0, a - (w.before == null ? 2 : w.before)); i <= Math.min(t.length - 1, b + (w.after == null ? 3 : w.after)); i++) {
        if (inList(t[i].normal || t[i].text, w.words)) return false;
      }
    }
    if (cond.excludeSentenceWords || cond.requireSentenceWords || cond.requireNoQuantity) {
      var foundRequired = !cond.requireSentenceWords;
      for (i = ctx.sentence.first; i <= ctx.sentence.last; i++) {
        var term = t[i];
        var word = term.normal || term.text;
        if (cond.excludeSentenceWords && inList(word, cond.excludeSentenceWords)) return false;
        if (cond.requireSentenceWords && inList(word, cond.requireSentenceWords)) foundRequired = true;
        if (cond.requireNoQuantity && hasAnyTag(term, QUANTITY_TAGS) && !hasTag(term, "Date")) return false;
      }
      if (!foundRequired) return false;
    }
    if (cond.excludeMidSentenceCapital) {
      // A Capitalized word is a proper name if it is mid-sentence, or if the next word is Capitalized too ("Radical Republicans", "Thug Life").
      if (/^[A-Z][a-z]/.test(ctx.text.slice(ctx.start, ctx.end))) {
        var nextTerm = t[b + 1];
        if (a !== ctx.sentence.first || (nextTerm && sameSentence(t, b, b + 1) && /^[A-Z][a-z]/.test(nextTerm.text))) return false;
      }
    }
    if (cond.excludeFollowingPattern) {
      var re = new RegExp("^" + spaced(cond.excludeFollowingPattern), "i");
      if (re.test(ctx.text.slice(ctx.end, ctx.end + 60))) return false;
    }
    return true;
  }

  function resolveNeutralAlternative(pattern, matchedText) {
    if (pattern.neutralAlternatives) {
      var override = pattern.neutralAlternatives[norm(matchedText)];
      if (override) return override;
    }
    return pattern.neutralAlternative || null;
  }

  function buildRecord(pattern, categories, cand, range, passed, failedAt) {
    var category = categories && categories[pattern.technique];
    return {
      id: pattern.id,
      technique: pattern.technique,
      category: pattern.technique,
      techniqueLabel: category ? category.label : pattern.technique,
      label: pattern.label,
      start: cand.start,
      end: cand.end,
      matchedText: cand.matchedText,
      tokenStart: range ? range[0] : null,
      tokenEnd: range ? range[1] : null,
      explanation: pattern.explanation,
      neutralAlternative: resolveNeutralAlternative(pattern, cand.matchedText),
      confidenceTier: pattern.confidenceTier,
      confidenceRank: TIER_RANK[pattern.confidenceTier] || 0,
      passed: passed,
      failedAt: failedAt
    };
  }

  /**
   * Every lexical candidate for every rule, each tagged with whether it
   * passed S and C (failedAt = "linguistic" | "context" | null).
   */
  function evaluate(text, patterns, categories, options) {
    var records = [];
    if (!text || !patterns || !patterns.length) return records;
    var terms = flattenTerms(text);
    var quotes = options && options.includeQuotes ? [] : quotedSpans(text);

    for (var p = 0; p < patterns.length; p++) {
      var pattern = patterns[p];
      var lexical = pattern.lexicalTrigger;
      if (!lexical || !lexical.pattern) continue;
      var re = new RegExp(spaced(lexical.pattern), "gi");
      var m;
      while ((m = re.exec(text)) !== null) {
        var cand = { start: m.index, end: m.index + m[0].length, matchedText: m[0] };
        if (m[0].length === 0) re.lastIndex++;

        var range = termRange(terms, cand.start, cand.end);
        var passed = true;
        var failedAt = null;
        if (range) {
          var ctx = {
            terms: terms, a: range[0], b: range[1], text: text, start: cand.start, end: cand.end,
            sentence: terms.sentences[terms[range[0]].sentenceIndex]
          };
          if (!evalLinguistic(pattern.linguisticCondition, ctx)) {
            passed = false;
            failedAt = "linguistic";
          } else if (!evalContext(pattern.contextCondition, ctx)) {
            passed = false;
            failedAt = "context";
          }
        }
        if (passed && !pattern.flagInsideQuotes && insideQuote(quotes, cand.start, cand.end)) {
          passed = false;
          failedAt = "quoted";
        }
        records.push(buildRecord(pattern, categories, cand, range, passed, failedAt));
      }
    }
    records.sort(function (x, y) {
      return x.start - y.start || (x.id < y.id ? -1 : x.id > y.id ? 1 : 0);
    });
    return records;
  }

  /**
   * @param {string} text - plain-text paragraph to scan.
   * @param {Array} patterns - `patterns` array from pattern-catalog.json.
   * @param {Object} categories - `techniques` map from pattern-catalog.json (for technique labels).
   * @param {{mode?: "full"|"lexicalOnly", includeQuotes?: boolean}} [options]
   * @returns {Array<Match>} matches sorted by start; overlap resolution is a separate stage.
   */
  function findMatches(text, patterns, categories, options) {
    var lexicalOnly = !!options && options.mode === "lexicalOnly";
    return evaluate(text, patterns, categories, options).filter(function (r) {
      return lexicalOnly || r.passed;
    });
  }

  return {
    findMatches: findMatches,
    evaluate: evaluate,
    quotedSpans: quotedSpans,
    LINGUISTIC_TYPES: LINGUISTIC_TYPES,
    _internals: { flattenTerms: flattenTerms, termRange: termRange, evalLinguistic: evalLinguistic, evalContext: evalContext }
  };
});
